on:
  push:
    branches:
        - main
        - "release/**"
    paths:
        - "src/**"
    pull_requsts:
        branches:
            - main
            - "release/**"
jobs:
    test:
        runs-on: macos-latest
        steps:
            - name: checkout
                uses: actions/checkout@v4.2.2
            - name: run tests
                run: npm test



